#!/bin/sh
#
# Description:
#    Page scrape doc links from http://www.syman.com/business/support/index?page=content&id=DOC6169&actp=SUBSCRIPTION
#

function _awk_parse_html() {
    local _input_filename="$1"

    awk 'BEGIN { 
    
    }
    
    {
    
    if ($0 ~ /<tr>/) {
        title="";
        desc="";
        link="";
    }
    
    if ($0 ~ /<td/) {
        if (title == "") {
            # Title.
            title=$0
            sub(/^.*<td[^>]*>/, "", title); 
            sub(/<\/td>.*$/, "", title);
            #printf("title=%s\n", title);
        } else {
            if ($0 ~ /.*http:\/\/www.syman.com\/docs\/.*/) {
                # Link.
                link=$0
                sub(/^.*<td[^>]*>.*<a href="/, "", link);
                sub(/">.*<\/a><\/td>/, "", link);
                #printf("link=%s\n", link);
                doc_links[title]=link
            }
        }
    }
    
    }
    END { 
 
    # Sort the links by description.
    printf("<table>\n");
    j=1;
    for (i in doc_links) {
        ind[j]=i;
        j++;
    }
    n=asort(ind);
    for (i=1; i<=n; i++) {
        _val=ind[i];
        printf("<tr><td><a href=\"%s\" target="_NEW">%s</a></td><td>%s</td></tr>\n", doc_links[_val], _val, doc_links[_val]);
    }
    printf("</table>\n");
    
    _date=strftime("%a %b %e %H:%M:%S %Z %Y");
    printf("<p>Generated by gendocshtml on %s</p>\n", _date);
    
    }' "$_input_filename"
}

# Description:
#   Parse documentation listings.
#
# Usage:
#   gendocshtml <url> <title>
#
# Example:
#   gendocshtml "http://www.syman.com/business/support/index?page=content&id=DOC6169&actp=SUBSCRIPTION" "7.1.2 Documentation"
#
function _gendocshtml() {
    if [ $# -ne 2 -o "$1" = '-h' ]; then
        usage _gendocshtml
        return
    fi

    local _url=$1
    local _title=$2

    $TOOLS_DIR/wget/wget -qO- "$_url" > "${TMP}/gendocshtml.tmp1"
    _awk_parse_html "${TMP}/gendocshtml.tmp1"  >"${TMP}/gendocshtml.tmp2"
    tac "${TMP}/gendocshtml.tmp2" > "${TMP}/gendocshtml.tmp1"
    cat <<EOI >> "${TMP}/gendocshtml.tmp1"
<html><title>$_title</title><body><h2>$_title</h2>
<p>Documentation Links extracted from <a href="$_url">$_url</a></p>
EOI
    tac "${TMP}/gendocshtml.tmp1"
}

# Description:
#   Parse documentation listings.
#
# Usage:
#   gendocshtml712
#
# Example:
#   gendocshtml712
#
function gendocshtml712() {
    if [ "$1" = '-h' ]; then
        usage gendocshtml712
        return
    fi

    _gendocshtml 'http://www.syman.com/business/support/index?page=content&id=DOC6169&actp=SUBSCRIPTION' '7.1.2 Documentation'
}


# Description:
#   Parse documentation listings.
#
# Usage:
#   gendocshtml713
#
# Example:
#   gendocshtml713
#
function gendocshtml713() {
    if [ "$1" = '-h' ]; then
        usage gendocshtml713
        return
    fi

    _gendocshtml 'http://www.syman.com/business/support/index?page=content&id=DOC6635&actp=SUBSCRIPTION' '7.1.3 Documentation'
}


# Description:
#   Parse documentation listings.
#
# Usage:
#   gendocshtml714
#
# Example:
#   gendocshtml714
#
function gendocshtml714() {
    if [ "$1" = '-h' ]; then
        usage gendocshtml714
        return
    fi

    _gendocshtml 'http://www.syman.com/business/support/index?page=content&id=DOC6836&actp=SUBSCRIPTION' '7.1.4 Documentation'
}


# Description:
#   Parse documentation listings.
#
# Usage:
#   gendocshtml715
#
# Example:
#   gendocshtml715
#
function gendocshtml715() {
    if [ "$1" = '-h' ]; then
        usage gendocshtml715
        return
    fi

    _gendocshtml 'http://www.syman.com/business/support/index?page=content&id=DOC7192&actp=SUBSCRIPTION' '7.1.5 Documentation'
}
